import Link from "next/link";
import { notFound } from "next/navigation";
import { AddToCartButton, StoreFooter, StoreHeader } from "../../storefront-context";
import { getProduct, products } from "../../store-data";

export function generateStaticParams(){return products.map(product=>({slug:product.slug}))}

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const product=getProduct(slug);if(!product)notFound();
  return <main className="brandSite"><StoreHeader/><section className="productDetail"><div className="productGallery" style={{"--accent":product.accent} as React.CSSProperties}><div className="productStamp">K1<br/><span>ESTD 2023</span></div>{product.image?<img src={product.image} alt={`${product.name} ${product.weight} jar packaging`}/>:<div className="genericPack"><img src="/k1-logo.jpeg" alt="K1 Nut's"/><span>{product.emoji}</span><b>{product.name}</b><small>PREMIUM · {product.weight}</small></div>}<div className="galleryNote">DESIGN MOCKUP · PACKAGING MAY EVOLVE</div></div><div className="productSummary"><div className="breadcrumbs"><Link href="/">HOME</Link><span>/</span><Link href={`/category/${product.categorySlug}`}>{product.category.toUpperCase()}</Link></div><p className="brandEyebrow"><span/> {product.badge??"K1 SELECTED"}</p><h1>{product.name}</h1><div className="stars">★★★★★ <span>4.9 · EARLY TASTER SCORE</span></div><p className="leadDescription">{product.description}</p><div className="priceLine"><b>₹{product.price}</b>{product.mrp>product.price&&<del>₹{product.mrp}</del>}<span>MRP · TAXES INCLUDED</span></div><div className="weightChoice"><span>PACK SIZE</span><button>{product.weight}</button></div><AddToCartButton product={product}/><div className="deliveryNotes"><span>✦ Free delivery above ₹799</span><span>✦ Freshness-sealed PET jar</span><span>✦ Shiprocket & Delhivery ready</span></div></div></section>
    <section className="productFacts sectionNew"><div><p className="brandEyebrow"><span/> WHAT&apos;S INSIDE</p><h2>Real ingredients.<br/><em>Nothing to hide.</em></h2><p>{product.short} Crafted for clean flavour and reliable everyday nourishment.</p></div><div className="ingredientList">{(product.ingredients??[product.name,"Natural ingredients","Freshness-sealed"]).map((ingredient,index)=><span key={ingredient}><b>{String(index+1).padStart(2,"0")}</b>{ingredient}</span>)}</div></section>
    {product.composition&&<section className="composition sectionNew"><div><p className="brandEyebrow light"><span/> APPROXIMATE COMPOSITION</p><h2>A balanced<br/><em>little powerhouse.</em></h2></div><div>{product.composition.map(([name,value])=><div className="compositionRow" key={name}><span>{name}</span><i><b style={{width:`${value}%`}}/></i><em>{value}%</em></div>)}</div></section>}
    <section className="benefitStrip">{(product.benefits??["Quality graded","Freshness packed","K1 selected","Made with care"]).map((benefit,index)=><span key={benefit}><b>0{index+1}</b>{benefit}</span>)}</section><section className="productStory"><img src="/k1-logo.jpeg" alt="K1 Nut's Delicacy from the Himalayas"/><div><p className="brandEyebrow"><span/> THE K1 PROMISE</p><h2>From our Himalayas,<br/><em>to your everyday.</em></h2><p>Selected with care, packed for freshness and made to bring better snacking into the rhythm of real life.</p><Link href={`/category/${product.categorySlug}`}>EXPLORE MORE {product.category.toUpperCase()} →</Link></div></section><StoreFooter/></main>
}

